<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScoreCrafter.Application\ScoreCrafter.Application.csproj" />
    <ProjectReference Include="..\ScoreCrafter.Domain\ScoreCrafter.Domain.csproj" />
    <ProjectReference Include="..\ScoreCrafter.Model\ScoreCrafter.SDK.Model.csproj" />
  </ItemGroup>

</Project>
