<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="protobuf-net.Grpc.AspNetCore.Reflection" Version="1.3.14" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.*" />
    <PackageReference Include="protobuf-net.Grpc.AspNetCore" Version="1.3.14" />
    <PackageReference Include="protobuf-net.Grpc.Reflection" Version="*" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />

    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScorCrafter.Infra.InMemoryQueue\ScoreCrafter.Infra.InMemoryQueue.csproj" />
    <ProjectReference Include="..\ScoreCrafter.Application\ScoreCrafter.Application.csproj" />
    <ProjectReference Include="..\ScoreCrafter.Domain\ScoreCrafter.Domain.csproj" />
    <ProjectReference Include="..\ScoreCrafter.Infra.Sqllite\ScoreCrafter.Infra.Sqllite.csproj" />
    <ProjectReference Include="..\ScoreCrafter.Model\ScoreCrafter.SDK.Model.csproj" />
  </ItemGroup>

</Project>
